# Generated by Django 5.2.9 on 2026-07-01 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Preço')),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Tempo estimado em minutos para a execução do serviço', verbose_name='Duração (Minutos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(help_text='Empresa a qual o serviço pertence', on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='tenants.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_hora_fim', models.DateTimeField(blank=True, help_text='Calculado automaticamente somando a duração dos serviços selecionados', null=True, verbose_name='Data/Hora de Fim')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='tenants.empresa', verbose_name='Empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('servicos', models.ManyToManyField(related_name='agendamentos', to='agenda.servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_hora_inicio'],
            },
        ),
    ]
