# Generated by Django 6.0.6 on 2026-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lucro_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro Líquido'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Comissão'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
