# Generated by Django 5.2.14 on 2026-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_servico_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro')], max_length=20, null=True, verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
