# Generated by Django 5.2.9 on 2026-07-04 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_metodo_pagamento_and_more'),
        ('tenants', '0004_alter_empresa_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data/Hora de Fim')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Bloqueio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='tenants.empresa', verbose_name='Empresa')),
                ('profissional', models.ForeignKey(blank=True, help_text='Deixe em branco para bloquear a agenda de todos os profissionais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de Horário',
                'verbose_name_plural': 'Bloqueios de Horário',
                'ordering': ['data_hora_inicio'],
            },
        ),
    ]
