# Generated by Django 5.2.9 on 2026-07-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_bloqueiohorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro')], max_length=20, null=True, verbose_name='Método de Pagamento'),
        ),
    ]
