# Generated by Django 6.0.6 on 2026-07-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendamento_metodo_pagamento'),
        ('tenants', '0004_alter_empresa_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=20, verbose_name='WhatsApp do Cliente')),
                ('data_desejada', models.DateField(verbose_name='Data Desejada')),
                ('horario_desejado', models.TimeField(verbose_name='Horário Desejado')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='tenants.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fila de Espera',
                'verbose_name_plural': 'Fila de Espera',
                'ordering': ['criado_em'],
            },
        ),
    ]
