# Generated by Django 5.2.9 on 2026-07-15 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_filaespera'),
        ('tenants', '0006_empresa_fidelidade_ativo_empresa_fidelidade_estilo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_selos_atual', models.IntegerField(default=0, verbose_name='Quantidade de Selos Atual')),
                ('premios_disponiveis', models.IntegerField(default=0, help_text='Incrementado quando o cliente atinge a meta de selos da empresa.', verbose_name='Prêmios Disponíveis')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_fidelidade', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_fidelidade', to='tenants.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cartão Fidelidade',
                'verbose_name_plural': 'Cartões Fidelidade',
                'unique_together': {('empresa', 'cliente')},
            },
        ),
    ]
