# Generated by Django 5.2.17 on 2026-10-01 01:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_cartaofidelidade'),
        ('tenants', '0010_sitevisitcounter'),
        ('vitrine', '0004_pedido_concluido_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=12)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro')], max_length=20, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_servicos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comanda', to='agenda.agendamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='tenants.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemComandaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='agenda.comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrine.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComandaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='agenda.comanda')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.servico')),
            ],
        ),
    ]
