# Generated by Django 5.2.9 on 2026-07-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROFISSIONAL', 'Profissional'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
