# Generated by Django 6.0.6 on 2026-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_telefone_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='taxa_comissao',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Percentual de comissão individual do profissional (ex: 40.0)', max_digits=5, verbose_name='Taxa de Comissão'),
        ),
    ]
