# Generated by Django 5.2.9 on 2026-07-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_taxa_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Nota do profissional (1.0 a 5.0)', max_digits=3, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/', verbose_name='Foto de Perfil'),
        ),
    ]
