# Generated by Django 5.2.9 on 2026-07-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_avaliacao_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Percentual de Comissão'),
        ),
    ]
