# Generated by Django 5.2.9 on 2026-07-17 21:45

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_comissao_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('EXIGIR_SINAL', 'Exigir Sinal (PIX)'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20, verbose_name='Status da Conta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profissional_foto_path, verbose_name='Foto de Perfil'),
        ),
    ]
