# Generated by Django 5.2.17 on 2026-10-01 00:27

from django.db import migrations, models


def preencher_conclusoes_existentes(apps, schema_editor):
    Pedido = apps.get_model('vitrine', 'Pedido')
    Pedido.objects.filter(status='CONCLUIDO', concluido_em__isnull=True).update(concluido_em=models.F('atualizado_em'))


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_pedido_token_ticket_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='concluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preencher_conclusoes_existentes, migrations.RunPython.noop),
    ]
