# Generated by Django 5.2.9 on 2026-07-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome fantasia da barbearia', max_length=255, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(help_text='Usado para subdomínios ou rotas na URL da barbearia', max_length=100, unique=True, verbose_name='Identificador Único (Slug)')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a empresa está ativa no SaaS', verbose_name='Ativo')),
                ('hora_abertura', models.TimeField(default='09:00:00', verbose_name='Horário de Abertura')),
                ('hora_fechamento', models.TimeField(default='19:00:00', verbose_name='Horário de Fechamento')),
                ('intervalo_almoco_inicio', models.TimeField(blank=True, null=True, verbose_name='Início do Intervalo de Almoço')),
                ('intervalo_almoco_fim', models.TimeField(blank=True, null=True, verbose_name='Fim do Intervalo de Almoço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
