# Generated by Django 6.0.6 on 2026-07-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assinatura_ativa',
            field=models.BooleanField(default=False, help_text='Indica se a barbearia possui uma assinatura paga e ativa.', verbose_name='Assinatura Ativa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_trial',
            field=models.BooleanField(default=True, help_text='Indica se a barbearia ainda está no Free Trial.', verbose_name='Em Período de Teste'),
        ),
    ]
