# Generated by Django 6.0.6 on 2026-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_empresa_assinatura_ativa_empresa_em_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_fim_trial',
            field=models.DateField(blank=True, help_text='Data em que o período de teste expira.', null=True, verbose_name='Fim do Período de Teste'),
        ),
    ]
