# Generated by Django 5.2.9 on 2026-07-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_empresa_data_fim_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, help_text='Usado para subdomínios ou rotas na URL da barbearia', max_length=100, null=True, unique=True, verbose_name='Identificador Único (Slug)'),
        ),
    ]
