# Generated by Django 5.2.9 on 2026-07-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dias_retorno_lembrete',
            field=models.IntegerField(default=25, help_text='Quantidade de dias após o último serviço para enviar o lembrete automático via WhatsApp.', verbose_name='Dias para lembrete de retorno'),
        ),
    ]
