# Generated by Django 5.2.9 on 2026-07-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_empresa_dias_retorno_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fidelidade_ativo',
            field=models.BooleanField(default=True, help_text='Ativa ou desativa o cartão fidelidade digital para os clientes.', verbose_name='Programa de Fidelidade Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fidelidade_estilo',
            field=models.CharField(choices=[('goku', 'Goku Super Saiyajin'), ('classic', 'Clássico (Joinhas / Tesouras)')], default='goku', help_text='Tema visual que será renderizado no painel do cliente.', max_length=50, verbose_name='Estilo Visual do Cartão'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fidelidade_meta',
            field=models.IntegerField(default=10, help_text='Quantidade de selos necessários para o cliente ganhar o prêmio.', verbose_name='Meta de Selos'),
        ),
    ]
