# Generated by Django 5.2.9 on 2026-07-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_empresa_fidelidade_ativo_empresa_fidelidade_estilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='beneficiario_pix',
            field=models.CharField(blank=True, default='', help_text='Nome da pessoa ou empresa que receberá o PIX.', max_length=150, verbose_name='Beneficiário do PIX'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='chave_pix',
            field=models.CharField(blank=True, default='', help_text='Chave PIX para recebimento do sinal.', max_length=100, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='exigir_sinal',
            field=models.BooleanField(default=False, help_text='Exige confirmação via PIX de 50% do valor do serviço.', verbose_name='Exigir Sinal (50%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horas_limite_cancelamento',
            field=models.PositiveIntegerField(default=24, help_text='Impede que o cliente cancele sozinho se faltar menos que X horas para o serviço.', verbose_name='Horas Limite para Cancelamento Automático'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fidelidade_estilo',
            field=models.CharField(choices=[('estrela', 'Estrela (Elegante / Unissex)'), ('cuidado', 'Cuidado (Feminino / Delicado)'), ('classic', 'Clássico (Neutro / Universal)'), ('goku', 'Goku (Legado)')], default='estrela', help_text='Tema visual que será renderizado no painel do cliente.', max_length=50, verbose_name='Estilo Visual do Cartão'),
        ),
    ]
