# Generated by Django 5.2.9 on 2026-07-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_empresa_beneficiario_pix_empresa_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_vencimento_assinatura',
            field=models.DateField(blank=True, help_text='Data de expiração da assinatura mensal.', null=True, verbose_name='Data de Vencimento da Assinatura'),
        ),
    ]
